// Turf smoothing but it's not
#define SMOOTH_GROUP_DEEP_WATER_HORIZON S_OBJ(1000)
#define SMOOTH_GROUP_SHALLOW_WATER_HORIZON S_OBJ(1001)
#define SMOOTH_GROUP_SLOPPLER_MUD S_OBJ(1002)
#define SMOOTH_GROUP_SLOPPLER_DIRT S_OBJ(1003)
#define SMOOTH_GROUP_SLOPPLER_SUPER_DIRT S_OBJ(1004)
#define SMOOTH_GROUP_WILD_STONE_FLOOR S_OBJ(1005)
// Wall smoothing
#define SMOOTH_GROUP_WILD_STONE_WALL S_OBJ(2000)
