#define AMBIENCE_FANTASY_SURFACE "fantasy_surface"

GLOBAL_LIST_INIT(fantasy_surface_ambience,list(
	'modular_sloppler/ambience/wind/1_Strike It Again.ogg',
	'modular_sloppler/ambience/wind/2_The Capital.ogg',
	'modular_sloppler/ambience/wind/3_Bruising The Fat (Shar Ikal).ogg',
	'modular_sloppler/ambience/wind/4_Life of Adventure.ogg',
	'modular_sloppler/ambience/wind/5_Beyond The Gates.ogg',
	'modular_sloppler/ambience/wind/6_Hamlet Memoirs.ogg',
	'modular_sloppler/ambience/wind/7_Night Creature.ogg',
	'modular_sloppler/ambience/wind/8_Into The Pits.ogg',
	'modular_sloppler/ambience/wind/9_Sisters of War.ogg',
	'modular_sloppler/ambience/wind/10_Cannibal.ogg',
	'modular_sloppler/ambience/wind/11_Pony Rider.ogg',
	'modular_sloppler/ambience/wind/12_Two Coins.ogg',
	'modular_sloppler/ambience/wind/13_Losing Is Fun.ogg',
	'modular_sloppler/ambience/wind/AY_Full.ogg',
	'modular_sloppler/ambience/wind/bonecrafter.ogg',
	'modular_sloppler/ambience/wind/CS_Full.ogg',
	'modular_sloppler/ambience/wind/cuggans_cove.ogg',
	'modular_sloppler/ambience/wind/dagger_dance.ogg',
	'modular_sloppler/ambience/wind/danger_room.ogg',
	'modular_sloppler/ambience/wind/decapitated_camels.ogg',
	'modular_sloppler/ambience/wind/DI_Full.ogg',
	'modular_sloppler/ambience/wind/dolomite_lullaby.ogg',
	'modular_sloppler/ambience/wind/DS_Full.ogg',
	'modular_sloppler/ambience/wind/EC_Full.ogg',
	'modular_sloppler/ambience/wind/emergence.ogg',
	'modular_sloppler/ambience/wind/encounter.ogg',
	'modular_sloppler/ambience/wind/FB_Full.ogg',
	'modular_sloppler/ambience/wind/FY_Full.ogg',
	'modular_sloppler/ambience/wind/galena.ogg',
	'modular_sloppler/ambience/wind/HD_Full.ogg',
	'modular_sloppler/ambience/wind/inith_and_od_travel_north.ogg',
	'modular_sloppler/ambience/wind/KG_Full.ogg',
	'modular_sloppler/ambience/wind/kobold_march.ogg',
	'modular_sloppler/ambience/wind/koganusan.ogg',
	'modular_sloppler/ambience/wind/MH_Full.ogg',
	'modular_sloppler/ambience/wind/SM_Full.ogg',
	'modular_sloppler/ambience/wind/spelunker.ogg',
	'modular_sloppler/ambience/wind/STE_Full.ogg',
	'modular_sloppler/ambience/wind/the_balanced_dunes.ogg',
	'modular_sloppler/ambience/wind/the_elves_of_the_coast.ogg',
	'modular_sloppler/ambience/wind/the_king_is_dead.ogg',
	'modular_sloppler/ambience/wind/the_storm_and_the_bounty.ogg',
	'modular_sloppler/ambience/wind/the_tankard_basher.ogg',
	'modular_sloppler/ambience/wind/VFOD_Full.ogg',
	'modular_sloppler/ambience/wind/WEY_Full.ogg',
	'modular_sloppler/ambience/wind/whip_vine.ogg',
	'modular_sloppler/ambience/wind/ztiq.ogg',
))
