#define AMBIENCE_FANTASY_SURFACE "fantasy_surface"

GLOBAL_LIST_INIT(fantasy_surface_ambience, list(
	'modular_sloppler/ambience/wind/1_Strike It Again.wav',
	'modular_sloppler/ambience/wind/2_The Capital.wav',
	'modular_sloppler/ambience/wind/3_Bruising The Fat (Shar Ikal).wav',
	'modular_sloppler/ambience/wind/4_Life of Adventure.wav',
	'modular_sloppler/ambience/wind/5_Beyond The Gates.wav',
	'modular_sloppler/ambience/wind/6_Hamlet Memoirs.wav',
	'modular_sloppler/ambience/wind/7_Night Creature.wav',
	'modular_sloppler/ambience/wind/8_Into The Pits.wav',
	'modular_sloppler/ambience/wind/9_Sisters of War.wav',
	'modular_sloppler/ambience/wind/10_Cannibal.wav',
	'modular_sloppler/ambience/wind/11_Pony Rider.wav',
	'modular_sloppler/ambience/wind/12_Two Coins.wav',
	'modular_sloppler/ambience/wind/13_Losing Is Fun.wav',
	'modular_sloppler/ambience/wind/AY_Full.wav',
	'modular_sloppler/ambience/wind/bonecrafter.wav',
	'modular_sloppler/ambience/wind/CS_Full.wav',
	'modular_sloppler/ambience/wind/cuggans_cove.wav',
	'modular_sloppler/ambience/wind/dagger_dance.wav',
	'modular_sloppler/ambience/wind/danger_room.wav',
	'modular_sloppler/ambience/wind/decapitated_camels.wav',
	'modular_sloppler/ambience/wind/DI_Full.wav',
	'modular_sloppler/ambience/wind/dolomite_lullaby.wav',
	'modular_sloppler/ambience/wind/DS_Full.wav',
	'modular_sloppler/ambience/wind/EC_Full.wav',
	'modular_sloppler/ambience/wind/emergence.wav',
	'modular_sloppler/ambience/wind/encounter.wav',
	'modular_sloppler/ambience/wind/FB_Full.wav',
	'modular_sloppler/ambience/wind/FY_Full.wav',
	'modular_sloppler/ambience/wind/galena.wav',
	'modular_sloppler/ambience/wind/HD_Full.wav',
	'modular_sloppler/ambience/wind/inith_and_od_travel_north.wav',
	'modular_sloppler/ambience/wind/KG_Full.wav',
	'modular_sloppler/ambience/wind/kobold_march.wav',
	'modular_sloppler/ambience/wind/koganusan.wav',
	'modular_sloppler/ambience/wind/MH_Full.wav',
	'modular_sloppler/ambience/wind/SM_Full.wav',
	'modular_sloppler/ambience/wind/spelunker.wav',
	'modular_sloppler/ambience/wind/STE_Full.wav',
	'modular_sloppler/ambience/wind/the_balanced_dunes.wav',
	'modular_sloppler/ambience/wind/the_elves_of_the_coast.wav',
	'modular_sloppler/ambience/wind/the_king_is_dead.wav',
	'modular_sloppler/ambience/wind/the_storm_and_the_bounty.wav',
	'modular_sloppler/ambience/wind/the_tankard_basher.wav',
	'modular_sloppler/ambience/wind/VFOD_Full.wav',
	'modular_sloppler/ambience/wind/WEY_Full.wav',
	'modular_sloppler/ambience/wind/whip_vine.wav',
	'modular_sloppler/ambience/wind/ztiq.wav',
))
